# Generated by Django 3.2 on 2022-12-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='depart_id',
            new_name='depart',
        ),
    ]
